cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'ack'
brew 'cabal-install'
brew 'chruby'
brew 'coreutils'
brew 'ctags'
brew 'elixir'
brew 'ghc'
brew 'git'
brew 'go'
brew 'haskell-stack'
brew 'highlight'
brew 'hub'
brew 'imagemagick'
brew 'node'
# brew 'phantomjs' This is currently broken in el cap.
brew 'postgresql'
brew 'redis'
brew 'ruby-install'
brew 'selecta'
brew 'the_silver_searcher'
brew 'tmux'
brew 'vim', args: ['with-lua', 'with-luajit']
brew 'zsh'

cask 'adium'
cask 'atom'
cask 'google-chrome'
cask 'mojibar'
cask 'slack'
cask 'virtualbox'
cask 'mojibar'
