cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'thoughtbot/formulae'

brew 'ack'
brew 'coreutils'
brew 'ctags'
brew 'emacs-plus'
brew 'fish'
brew 'git'
brew 'git-standup'
brew 'graphviz'
brew 'heroku'
brew 'highlight'
brew 'hub'
brew 'imagemagick'
brew 'phantomjs'
brew 'postgres'
brew 'rcm'
brew 'selecta'
brew 'the_silver_searcher'
brew 'tmux'
brew 'vim', args: ['with-lua', 'with-luajit']
brew 'wget'


cask '1password'
cask 'atom'
cask 'docker'
cask 'gpgtools'
cask 'iterm2'
cask 'imageoptim'
cask 'licecap'
cask 'ngrok'
cask 'slack'
